# You can make apps auto-start here
# Relevant Hyprland wiki section: https://wiki.hyprland.org/Configuring/Keywords/#executing

# Auto-detect and apply monitor profile on startup
exec-once = ~/.config/hypr/scripts/monitor-switch.sh auto

# Wallpaper
exec-once = hyprpaper
